<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="TX717-4441WGD" name="Default test" tests="1" failures="1" timestamp="12 Apr 2017 19:09:20 GMT" time="20.667" errors="0">
  <testcase name="runTC_SF_API_Accounts" time="20.636" classname="testscripts.SF.SmokeTest_API.TC_SF_API_Accounts">
    <failure type="com.cognizant.framework.FrameworkException" message="Exception thrown while adding a picture file to a Word document">
      <![CDATA[com.cognizant.framework.FrameworkException: Exception thrown while adding a picture file to a Word document
	at com.cognizant.framework.WordDocumentManager.addPicture(WordDocumentManager.java:127)
	at com.cognizant.framework.Report.consolidateScreenshotsInWordDoc(Report.java:369)
	at com.cognizant.Craft.DriverScript.closeTestReport(DriverScript.java:783)
	at com.cognizant.Craft.DriverScript.wrapUp(DriverScript.java:774)
	at com.cognizant.Craft.DriverScript.driveTestExecution(DriverScript.java:157)
	at testscripts.SF.SmokeTest_API.TC_SF_API_Accounts.runTC_SF_API_Accounts(TC_SF_API_Accounts.java:32)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
    </failure>
  </testcase> <!-- runTC_SF_API_Accounts -->
</testsuite> <!-- Default test -->
